# coding=utf-8

# url

LOGIN_URL = {
    'cmcc': {
        'init_page': 'https://login.10086.cn/login.html',
        'load_sendflag': 'https://login.10086.cn/loadSendflag.htm?timestamp=',
        'captchazh': 'https://login.10086.cn/captchazh.htm?type=12',
        'genqr': 'https://login.10086.cn/genqr.htm',
        'check_uid': 'https://login.10086.cn/checkUidAvailable.action',
        'check_number': 'https://login.10086.cn/chkNumberAction.action',
        'load_token': 'https://login.10086.cn/loadToken.action',
        'send_code': 'https://login.10086.cn/sendRandomCodeAction.action',
        'send_flag': 'https://login.10086.cn/sendflag.htm',
        'login': 'https://login.10086.cn/login.htm'
    },
    'cu': {
        'call_dan_iframe': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
        'e4avatar_upload': 'https://iservice.10010.com/e4/jsonp/e4avatar_upload.html',
        'get_head_img': 'https://uac.10010.com/portal/Service/getHeadImg',
        'search_per_info': 'https://iservice.10010.com/e3/static/query/searchPerInfo/',
        'search_per_info_user': 'https://iservice.10010.com/e3/static/query/searchPerInfoUser/',
        'page_list': 'https://iservice.10010.com/e3/static/query/message/pageList',
        'checklogin': 'https://iservice.10010.com/e3/static/check/checklogin/?_={0}',
        'cust_login': 'https://uac.10010.com/portal/custLogin',
        'call_dan': 'https://iservice.10010.com/e4/query/bill/call_dan.html?menuId=000100030001',
        'get_js': 'https://iservice.10010.com/e3/static/transact/getJs?_={0}?_={1}&accessURL=https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
        'checklogin2': 'https://www.10010.com/mall/service/check/checklogin/?_={0}',
        'info': 'https://iservice.10010.com/e3/static/common/info?_={0}',
        'shopping': 'https://iservice.10010.com/e3/static/shopping/g',
        'query_navigations': 'https://www.10010.com/mall/service/query/QueryNavigations',
        'get_area_by_ip': 'https://www.10010.com/mall/service/ipAddress/getAreaByIp/?_={0}',
        'check_need_verify': 'https://uac.10010.com/portal/Service/CheckNeedVerify',
        'send_ck_msg': 'https://uac.10010.com/portal/Service/SendCkMSG',
        'mall_login': 'https://uac.10010.com/portal/Service/MallLogin',
    },
    'ct': {
        'first_request': 'http://www.189.cn/dqmh/system.do?operate=index',
        'home_page': 'http://www.189.cn',
        'login_index': 'http://www.189.cn/login/index.do',
        'check_phone': 'https://login.189.cn/web/login/ajax',
        'captcha': 'https://login.189.cn/web/captcha',
        'mail_verify': 'https://login.189.cn/web/login/ajax',
        'validate_url': 'https://login.189.cn/web/pwd/validate',
        'login': 'https://login.189.cn/web/login',
        'user_page': 'https://www.189.cn/dqmh/my189/initMy189home.do'
    }
}


# headers

LOGIN_HEADERS = {
    'cmcc': {
        'init_page': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'cross-site',
            'Sec-Fetch-User': '?1',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36'
        },
        'load_sendflag': {
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36'
        },
        'captchazh': {
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
        },
        'genqr': {
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36'
        },
        'check_uid': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Host': 'login.10086.cn',
            'Origin': 'https://login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest',
        },
        'check_number': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '49',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Host': 'login.10086.cn',
            'Origin': 'https://login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'load_token': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '20',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Host': 'login.10086.cn',
            'Origin': 'https://login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'send_code': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '44',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Host': 'login.10086.cn',
            'Origin': 'https://login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest',
            'Xa-before': '',        # token 需要添加
        },
        'send_flag': {
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
        },
        'login': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest',
        },
        'artifact': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'www1.10086.cn',
            'Referer': 'https://login.10086.cn/login.html',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'same-site',
            'Sec-Fetch-User': '?1',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36'
        },
    },
    'cu': {
        'call_dan_iframe': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'iservice.10010.com',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'none',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
        },
        'e4avatar_upload': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'nested-navigate',
            'Sec-Fetch-Site': 'same-origin',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'get_head_img': {
            'Accept': '*/*',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'uac.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'search_per_info': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            'Host': 'iservice.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'search_per_info_user': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            'Host': 'iservice.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'page_list': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'checklogin': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Host': 'iservice.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'cust_login': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'uac.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'nested-navigate',
            'Sec-Fetch-Site': 'same-site',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'call_dan': {
            'Accept': 'text/html, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'get_js': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            'Host': 'iservice.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'checklogin2': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '18',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Host': 'www.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'info': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            'Host': 'iservice.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'shopping': {
            'Accept': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'query_navigations': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '30',
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            'Host': 'www.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'get_area_by_ip': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Host': 'www.10010.com',
            'Origin': 'https://iservice.10010.com',
            'Referer': 'https://iservice.10010.com/e4/query/bill/call_dan-iframe.html',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
        },
        'check_need_verify': {
            'Accept': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'uac.10010.com',
            'Referer': 'https://uac.10010.com/portal/custLogin',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'send_ck_msg': {
            'Accept': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'uac.10010.com',
            'Referer': 'https://uac.10010.com/portal/custLogin',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'mall_login': {
            'Accept': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'uac.10010.com',
            'Referer': 'https://uac.10010.com/portal/custLogin',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        }
    },
    'ct': {
        'origin': {
            'Host': 'www.189.cn',
            'Content-Length': '0',
            'Origin': 'http://www.189.cn',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
            'Accept': '*/*',
            'Referer': 'http://www.189.cn/',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive'
            },
        'login_index': {
            'Host': 'www.189.cn',
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'X-Requested-With': 'XMLHttpRequest',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
            'Referer': 'http://www.189.cn/html/login/index.html',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive'
        },
        'check_phone': {
            'Host': 'login.189.cn',
            'Connection': 'keep-alive',
            'Content-Length': '30',
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Origin': 'https://login.189.cn',
            'X-Requested-With': 'XMLHttpRequest',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
            'Sec-Fetch-Mode': 'cors',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Sec-Fetch-Site': 'same-origin',
            'Referer': 'https://login.189.cn/web/login',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
        },
        'captcha_headers': {
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Host': 'login.189.cn',
            'Referer': 'https://login.189.cn/web/login',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        },
        'mail_verify': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '64',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Host': 'login.189.cn',
            'Origin': 'https://login.189.cn',
            'Referer': 'https://login.189.cn/web/login',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest',
        },
        'validate_headers': {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Connection': 'keep-alive',
            'Content-Length': '78',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Host': 'login.189.cn',
            'Origin': 'https://login.189.cn',
            'Referer': 'https://login.189.cn/web/login',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        },
        'login_headers': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Connection': 'keep-alive',
            'Content-Length': '127',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Host': 'login.189.cn',
            'Origin': 'https://login.189.cn',
            'Referer': 'https://login.189.cn/web/login',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'same-origin',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36'
        },
        'ecs_headers': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Host': 'www.189.cn',
            'Proxy-Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        },
        'redirect_headers': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Host': 'www.189.cn',
            'Proxy-Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        },
        'each_prov_headers': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Host': 'www.189.cn',
            'Proxy-Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',

        },
        'user_headers': {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'max-age=0',
            'Host': 'www.189.cn',
            'Proxy-Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        }
    }
}


# #############################################################################
# ###################### 针对登录过程中用到的参数 ################################
# ############################################################################

# GET 请求

LOGIN_PARAMS = {
    'cmcc': {
        'send_flag': {
            'timestamp': '',  # 时间戳
        },
        'login': {
            'accountType': '01',
            'account': '',  # 手机号
            'password': '',  # 加密后的密码
            'pwdType': '01',
            'smsPwd': '',  # 短信验证码
            'inputCode': '',
            'backUrl': 'http://www.10086.cn/index/sc/index_280_280.html',   # 这里仅仅是针对四川
            'rememberMe': '0',
            'channelID': '12034',
            'loginMode': '01',
            'protocol': 'https:',
            'timestamp': '',  # 时间戳
        },
        'artifact': {
            'backUrl': 'http://www.10086.cn/index/sc/index_280_280.html',
            'artifact': '',  # artifact
            'type': '00'
        }
    },
    'cu': {
        'get_head_img': {
            'callback': 'jQuery1123011424774332753085_{}',
            '_': ''
        },
        'page_list': {
            '_': '',
            'currentPage': '1',
            'pageSize': '2'
        },
        'shopping': {
            'callback': 'jQuery1123011424774332753085_{0}',
            '_': ''
        },
        'check_need_verify': {
            'callback': 'jQuery17203665895120244169_{0}',
            'userName': '',
            'pwdType': '01',
            '_': ''
        },
        'send_ck_msg': {
            'callback': 'jQuery17203665895120244169_{0}',
            'req_time': '',
            'mobile': '',
            '_': ''
        },
        'mall_login': {
            'callback': 'jQuery17203665895120244169_{0}',
            'req_time': '',
            'redirectURL': 'http://www.10010.com',
            'userName': '18582481785',
            'password': '',
            'pwdType': '01',
            'productType': '01',
            'redirectType': '06',
            'rememberMe': '1',
            'verifyCKCode': '',
            '_': ''
        }
    },
    'ct': {
        'captcha_params': {
            'undefined': '',
            'source': 'login',
            'width': '100',
            'height': '37'
        },
    }
}

# POST请求

LOGIN_PAYLOADS = {
    'cmcc': {
        'check_number': {
            'userName': '',  # 手机号
            'loginMode': '01',
            'channelID': '10000'
        },
        'load_token': {
            'userName': '',  # 手机号
        },
        'send_code': {
            'userName': '',  # 手机号
            'type': '01',
            'channelID': '12034'
        }
    },
    'cu': {
        'search_per_info': {
            '_': ''
        },
        'search_per_info_user': {
            '_': ''
        },
        'checklogin2': {
            'jutThird': '',
            '_uop_id': ''
        },
        'query_navigations': {
            'jutThird': '',
            '_uop_id': '',
            'procode': '011'
        }
    },
    'ct': {
        'check_payloads_1': {
            'm': 'checkphone',
            'phone': '',        # 手机号
        },
        'check_payloads_2': {
            'm': 'captcha',
            'account': '',      # 手机号
            'uType': '201',
            'ProvinceID': '',   # 省份id
            'areaCode': '',
            'cityNo': ''
        },
        'vaildate_payloads': {
            'uName': '',    # 手机号
            'uType': '201',
            'uPwd': '',     # 计算出的手机号
            'isRandomPwd': 'true',
        },
        'login_payloads': {
            'Account': '',  # 手机号
            'UType': '201',
            'ProvinceID': '',   # 省份
            'AreaCode': '',
            'CityNo': '',
            'Captcha': '',  # 验证码
            'RandomFlag': '1',
            'Password': '',     # 密码
        },
        'login_mail': {
            'm': 'sendphonepwd',
            'account': '',  # 手机号
            'uType': '201',
            'pid': '',  # 省份
            'captcha': '',  # 验证码
        }
    }
}

"""
 #########################################################################
 #########################################################################
 ################ 作为清洗联通的省份和城市 ###################################
 #########################################################################
 #########################################################################
"""


PROV_LIST = {
    '北京': {'cityCode': '110', 'cityName': '北京', 'provinceCode': '11', 'provinceName': '北京'},
    '天津': {'cityCode': '130', 'cityName': '天津', 'provinceCode': '13', 'provinceName': '天津'},
    '河北': {'cityCode': '188', 'cityName': '石家庄', 'provinceCode': '18', 'provinceName': '河北'},
    '山西': {'cityCode': '190', 'cityName': '太原', 'provinceCode': '19', 'provinceName': '山西'},
    '内蒙古': {'cityCode': '101', 'cityName': '呼和浩特', 'provinceCode': '10', 'provinceName': '内蒙古'},
    '辽宁': {'cityCode': '910', 'cityName': '沈阳', 'provinceCode': '91', 'provinceName': '辽宁'},
    '吉林': {'cityCode': '901', 'cityName': '长春', 'provinceCode': '90', 'provinceName': '吉林'},
    '黑龙江': {'cityCode': '971', 'cityName': '哈尔滨', 'provinceCode': '97', 'provinceName': '黑龙江'},
    '上海': {'cityCode': '310', 'cityName': '上海', 'provinceCode': '31', 'provinceName': '上海'},
    '江苏': {'cityCode': '340', 'cityName': '南京', 'provinceCode': '34', 'provinceName': '江苏'},
    '浙江': {'cityCode': '360', 'cityName': '杭州', 'provinceCode': '36', 'provinceName': '浙江'},
    '安徽': {'cityCode': '305', 'cityName': '合肥', 'provinceCode': '30', 'provinceName': '安徽'},
    '福建': {'cityCode': '380', 'cityName': '福州', 'provinceCode': '38', 'provinceName': '福建'},
    '江西': {'cityCode': '750', 'cityName': '南昌', 'provinceCode': '75', 'provinceName': '江西'},
    '山东': {'cityCode': '170', 'cityName': '济南', 'provinceCode': '17', 'provinceName': '山东'},
    '河南': {'cityCode': '760', 'cityName': '郑州', 'provinceCode': '76', 'provinceName': '河南'},
    '湖北': {'cityCode': '710', 'cityName': '武汉', 'provinceCode': '71', 'provinceName': '湖北'},
    '海南': {'cityCode': '501', 'cityName': '海口', 'provinceCode': '50', 'provinceName': '海南'},
    '广东': {'cityCode': '510', 'cityName': '广州', 'provinceCode': '51', 'provinceName': '广东'},
    '广西': {'cityCode': '591', 'cityName': '南宁', 'provinceCode': '59', 'provinceName': '广西'},
    '湖南': {'cityCode': '741', 'cityName': '长沙', 'provinceCode': '74', 'provinceName': '湖南'},
    '重庆': {'cityCode': '831', 'cityName': '重庆', 'provinceCode': '83', 'provinceName': '重庆'},
    '四川': {'cityCode': '810', 'cityName': '成都', 'provinceCode': '81', 'provinceName': '四川'},
    '贵州': {'cityCode': '850', 'cityName': '贵阳', 'provinceCode': '85', 'provinceName': '贵州'},
    '云南': {'cityCode': '860', 'cityName': '昆明', 'provinceCode': '86', 'provinceName': '云南'},
    '西藏': {'cityCode': '790', 'cityName': '拉萨', 'provinceCode': '79', 'provinceName': '西藏'},
    '陕西': {'cityCode': '841', 'cityName': '西安', 'provinceCode': '84', 'provinceName': '陕西'},
    '甘肃': {'cityCode': '870', 'cityName': '兰州', 'provinceCode': '87', 'provinceName': '甘肃'},
    '青海': {'cityCode': '700', 'cityName': '西宁', 'provinceCode': '70', 'provinceName': '青海'},
    '宁夏': {'cityCode': '880', 'cityName': '银川', 'provinceCode': '88', 'provinceName': '宁夏'},
    '新疆': {'cityCode': '890', 'cityName': '乌鲁木齐', 'provinceCode': '89', 'provinceName': '新疆'},
    '香港': {'cityCode': 'HK', 'cityName': '香港', 'provinceCode': 'HK', 'provinceName': '香港'}
}

CITY_LIST = {
    '金昌': {'city_id': '930', 'prov_id': '87', 'prov_name': '甘肃'},
    '陇南': {'city_id': '960', 'prov_id': '87', 'prov_name': '甘肃'},
    '定西': {'city_id': '871', 'prov_id': '87', 'prov_name': '甘肃'},
    '庆阳': {'city_id': '873', 'prov_id': '87', 'prov_name': '甘肃'},
    '天水': {'city_id': '877', 'prov_id': '87', 'prov_name': '甘肃'},
    '白银': {'city_id': '879', 'prov_id': '87', 'prov_name': '甘肃'},
    '甘南': {'city_id': '961', 'prov_id': '87', 'prov_name': '甘肃'},
    '酒泉': {'city_id': '931', 'prov_id': '87', 'prov_name': '甘肃'},
    '临夏': {'city_id': '878', 'prov_id': '87', 'prov_name': '甘肃'},
    '兰州': {'city_id': '870', 'prov_id': '87', 'prov_name': '甘肃'},
    '平凉': {'city_id': '872', 'prov_id': '87', 'prov_name': '甘肃'},
    '嘉峪关': {'city_id': '876', 'prov_id': '87', 'prov_name': '甘肃'},
    '武威': {'city_id': '874', 'prov_id': '87', 'prov_name': '甘肃'},
    '张掖': {'city_id': '875', 'prov_id': '87', 'prov_name': '甘肃'},
    '郴州': {'city_id': '748', 'prov_id': '74', 'prov_name': '湖南'},
    '湘潭': {'city_id': '743', 'prov_id': '74', 'prov_name': '湖南'},
    '长沙': {'city_id': '741', 'prov_id': '74', 'prov_name': '湖南'},
    '永州': {'city_id': '796', 'prov_id': '74', 'prov_name': '湖南'},
    '娄底': {'city_id': '791', 'prov_id': '74', 'prov_name': '湖南'},
    '株洲': {'city_id': '742', 'prov_id': '74', 'prov_name': '湖南'},
    '怀化': {'city_id': '795', 'prov_id': '74', 'prov_name': '湖南'},
    '邵阳': {'city_id': '792', 'prov_id': '74', 'prov_name': '湖南'},
    '常德': {'city_id': '749', 'prov_id': '74', 'prov_name': '湖南'},
    '衡阳': {'city_id': '744', 'prov_id': '74', 'prov_name': '湖南'},
    '湘西': {'city_id': '793', 'prov_id': '74', 'prov_name': '湖南'},
    '岳阳': {'city_id': '745', 'prov_id': '74', 'prov_name': '湖南'},
    '益阳': {'city_id': '747', 'prov_id': '74', 'prov_name': '湖南'},
    '张家界': {'city_id': '794', 'prov_id': '74', 'prov_name': '湖南'},
    '河源': {'city_id': '670', 'prov_id': '51', 'prov_name': '广东'},
    '云浮': {'city_id': '538', 'prov_id': '51', 'prov_name': '广东'},
    '东莞': {'city_id': '580', 'prov_id': '51', 'prov_name': '广东'},
    '清远': {'city_id': '535', 'prov_id': '51', 'prov_name': '广东'},
    '汕尾': {'city_id': '525', 'prov_id': '51', 'prov_name': '广东'},
    '梅州': {'city_id': '528', 'prov_id': '51', 'prov_name': '广东'},
    '深圳': {'city_id': '540', 'prov_id': '51', 'prov_name': '广东'},
    '阳江': {'city_id': '565', 'prov_id': '51', 'prov_name': '广东'},
    '佛山': {'city_id': '530', 'prov_id': '51', 'prov_name': '广东'},
    '湛江': {'city_id': '520', 'prov_id': '51', 'prov_name': '广东'},
    '揭阳': {'city_id': '526', 'prov_id': '51', 'prov_name': '广东'},
    '中山': {'city_id': '556', 'prov_id': '51', 'prov_name': '广东'},
    '汕头': {'city_id': '560', 'prov_id': '51', 'prov_name': '广东'},
    '茂名': {'city_id': '568', 'prov_id': '51', 'prov_name': '广东'},
    '肇庆': {'city_id': '536', 'prov_id': '51', 'prov_name': '广东'},
    '潮州': {'city_id': '531', 'prov_id': '51', 'prov_name': '广东'},
    '江门': {'city_id': '550', 'prov_id': '51', 'prov_name': '广东'},
    '珠海': {'city_id': '620', 'prov_id': '51', 'prov_name': '广东'},
    '惠州': {'city_id': '570', 'prov_id': '51', 'prov_name': '广东'},
    '韶关': {'city_id': '558', 'prov_id': '51', 'prov_name': '广东'},
    '广州': {'city_id': '510', 'prov_id': '51', 'prov_name': '广东'},
    '白沙': {'city_id': 'A14', 'prov_id': '50', 'prov_name': '海南'},
    '琼中': {'city_id': 'A08', 'prov_id': '50', 'prov_name': '海南'},
    '昌江': {'city_id': 'A15', 'prov_id': '50', 'prov_name': '海南'},
    '儋州': {'city_id': '503', 'prov_id': '50', 'prov_name': '海南'},
    '五指山': {'city_id': 'A13', 'prov_id': '50', 'prov_name': '海南'},
    '临高': {'city_id': 'A18', 'prov_id': '50', 'prov_name': '海南'},
    '海口': {'city_id': '501', 'prov_id': '50', 'prov_name': '海南'},
    '定安': {'city_id': 'A01', 'prov_id': '50', 'prov_name': '海南'},
    '保亭': {'city_id': 'A09', 'prov_id': '50', 'prov_name': '海南'},
    '陵水': {'city_id': 'A11', 'prov_id': '50', 'prov_name': '海南'},
    '万宁': {'city_id': 'A07', 'prov_id': '50', 'prov_name': '海南'},
    '东方': {'city_id': 'A16', 'prov_id': '50', 'prov_name': '海南'},
    '三亚': {'city_id': '502', 'prov_id': '50', 'prov_name': '海南'},
    '澄迈': {'city_id': 'A02', 'prov_id': '50', 'prov_name': '海南'},
    '琼海': {'city_id': 'A04', 'prov_id': '50', 'prov_name': '海南'},
    '屯昌': {'city_id': 'A05', 'prov_id': '50', 'prov_name': '海南'},
    '乐东': {'city_id': 'A10', 'prov_id': '50', 'prov_name': '海南'},
    '文昌': {'city_id': 'A06', 'prov_id': '50', 'prov_name': '海南'},
    '张家口': {'city_id': '184', 'prov_id': '18', 'prov_name': '河北'},
    '邯郸': {'city_id': '186', 'prov_id': '18', 'prov_name': '河北'},
    '承德': {'city_id': '189', 'prov_id': '18', 'prov_name': '河北'},
    '保定': {'city_id': '187', 'prov_id': '18', 'prov_name': '河北'},
    '秦皇岛': {'city_id': '182', 'prov_id': '18', 'prov_name': '河北'},
    '邢台': {'city_id': '185', 'prov_id': '18', 'prov_name': '河北'},
    '衡水': {'city_id': '720', 'prov_id': '18', 'prov_name': '河北'},
    '石家庄': {'city_id': '188', 'prov_id': '18', 'prov_name': '河北'},
    '沧州': {'city_id': '180', 'prov_id': '18', 'prov_name': '河北'},
    '唐山': {'city_id': '181', 'prov_id': '18', 'prov_name': '河北'},
    '廊坊': {'city_id': '183', 'prov_id': '18', 'prov_name': '河北'},
    '怒江': {'city_id': '734', 'prov_id': '86', 'prov_name': '云南'},
    '普洱': {'city_id': '869', 'prov_id': '86', 'prov_name': '云南'},
    '丽江': {'city_id': '863', 'prov_id': '86', 'prov_name': '云南'},
    '西双版纳': {'city_id': '736', 'prov_id': '86', 'prov_name': '云南'},
    '昭通': {'city_id': '867', 'prov_id': '86', 'prov_name': '云南'},
    '文山': {'city_id': '732', 'prov_id': '86', 'prov_name': '云南'},
    '保山': {'city_id': '731', 'prov_id': '86', 'prov_name': '云南'},
    '昆明': {'city_id': '860', 'prov_id': '86', 'prov_name': '云南'},
    '迪庆': {'city_id': '735', 'prov_id': '86', 'prov_name': '云南'},
    '大理': {'city_id': '862', 'prov_id': '86', 'prov_name': '云南'},
    '曲靖': {'city_id': '866', 'prov_id': '86', 'prov_name': '云南'},
    '楚雄': {'city_id': '864', 'prov_id': '86', 'prov_name': '云南'},
    '玉溪': {'city_id': '8601', 'prov_id': '86', 'prov_name': '云南'},
    '临沧': {'city_id': '8602', 'prov_id': '86', 'prov_name': '云南'},
    '红河': {'city_id': '8603', 'prov_id': '86', 'prov_name': '云南'},
    '德宏': {'city_id': '8604', 'prov_id': '86', 'prov_name': '云南'},
    '六盘水': {'city_id': '853', 'prov_id': '85', 'prov_name': '贵州'},
    '黔南': {'city_id': '788', 'prov_id': '85', 'prov_name': '贵州'},
    '贵阳': {'city_id': '850', 'prov_id': '85', 'prov_name': '贵州'},
    '黔东南': {'city_id': '786', 'prov_id': '85', 'prov_name': '贵州'},
    '遵义': {'city_id': '787', 'prov_id': '85', 'prov_name': '贵州'},
    '黔西南': {'city_id': '852', 'prov_id': '85', 'prov_name': '贵州'},
    '毕节': {'city_id': '851', 'prov_id': '85', 'prov_name': '贵州'},
    '铜仁': {'city_id': '785', 'prov_id': '85', 'prov_name': '贵州'},
    '安顺': {'city_id': '789', 'prov_id': '85', 'prov_name': '贵州'},
    '商洛': {'city_id': '847', 'prov_id': '84', 'prov_name': '陕西'},
    '铜川': {'city_id': '846', 'prov_id': '84', 'prov_name': '陕西'},
    '延安': {'city_id': '842', 'prov_id': '84', 'prov_name': '陕西'},
    '汉中': {'city_id': '849', 'prov_id': '84', 'prov_name': '陕西'},
    '西安': {'city_id': '841', 'prov_id': '84', 'prov_name': '陕西'},
    '宝鸡': {'city_id': '840', 'prov_id': '84', 'prov_name': '陕西'},
    '安康': {'city_id': '848', 'prov_id': '84', 'prov_name': '陕西'},
    '榆林': {'city_id': '845', 'prov_id': '84', 'prov_name': '陕西'},
    '渭南': {'city_id': '843', 'prov_id': '84', 'prov_name': '陕西'},
    '咸阳': {'city_id': '8401', 'prov_id': '84', 'prov_name': '陕西'},
    '宜宾': {'city_id': '817', 'prov_id': '81', 'prov_name': '四川'},
    '眉山': {'city_id': '819', 'prov_id': '81', 'prov_name': '四川'},
    '南充': {'city_id': '822', 'prov_id': '81', 'prov_name': '四川'},
    '广安': {'city_id': '823', 'prov_id': '81', 'prov_name': '四川'},
    '攀枝花': {'city_id': '813', 'prov_id': '81', 'prov_name': '四川'},
    '广元': {'city_id': '826', 'prov_id': '81', 'prov_name': '四川'},
    '凉山': {'city_id': '812', 'prov_id': '81', 'prov_name': '四川'},
    '遂宁': {'city_id': '821', 'prov_id': '81', 'prov_name': '四川'},
    '资阳': {'city_id': '830', 'prov_id': '81', 'prov_name': '四川'},
    '雅安': {'city_id': '811', 'prov_id': '81', 'prov_name': '四川'},
    '自贡': {'city_id': '818', 'prov_id': '81', 'prov_name': '四川'},
    '绵阳': {'city_id': '824', 'prov_id': '81', 'prov_name': '四川'},
    '巴中': {'city_id': '827', 'prov_id': '81', 'prov_name': '四川'},
    '阿坝': {'city_id': '829', 'prov_id': '81', 'prov_name': '四川'},
    '成都': {'city_id': '810', 'prov_id': '81', 'prov_name': '四川'},
    '乐山': {'city_id': '814', 'prov_id': '81', 'prov_name': '四川'},
    '内江': {'city_id': '816', 'prov_id': '81', 'prov_name': '四川'},
    '达州': {'city_id': '820', 'prov_id': '81', 'prov_name': '四川'},
    '德阳': {'city_id': '825', 'prov_id': '81', 'prov_name': '四川'},
    '泸州': {'city_id': '8101', 'prov_id': '81', 'prov_name': '四川'},
    '甘孜': {'city_id': '8102', 'prov_id': '81', 'prov_name': '四川'},
    '林芝': {'city_id': '799', 'prov_id': '79', 'prov_name': '西藏'},
    '拉萨': {'city_id': '790', 'prov_id': '79', 'prov_name': '西藏'},
    '山南': {'city_id': '798', 'prov_id': '79', 'prov_name': '西藏'},
    '那曲': {'city_id': '801', 'prov_id': '79', 'prov_name': '西藏'},
    '日喀则': {'city_id': '797', 'prov_id': '79', 'prov_name': '西藏'},
    '昌都': {'city_id': '800', 'prov_id': '79', 'prov_name': '西藏'},
    '阿里': {'city_id': '802', 'prov_id': '79', 'prov_name': '西藏'},
    '南阳': {'city_id': '777', 'prov_id': '76', 'prov_name': '河南'},
    '濮阳': {'city_id': '773', 'prov_id': '76', 'prov_name': '河南'},
    '焦作': {'city_id': '763', 'prov_id': '76', 'prov_name': '河南'},
    '新乡': {'city_id': '764', 'prov_id': '76', 'prov_name': '河南'},
    '平顶山': {'city_id': '769', 'prov_id': '76', 'prov_name': '河南'},
    '鹤壁': {'city_id': '774', 'prov_id': '76', 'prov_name': '河南'},
    '周口': {'city_id': '770', 'prov_id': '76', 'prov_name': '河南'},
    '开封': {'city_id': '762', 'prov_id': '76', 'prov_name': '河南'},
    '济源': {'city_id': '775', 'prov_id': '76', 'prov_name': '河南'},
    '许昌': {'city_id': '765', 'prov_id': '76', 'prov_name': '河南'},
    '安阳': {'city_id': '767', 'prov_id': '76', 'prov_name': '河南'},
    '洛阳': {'city_id': '761', 'prov_id': '76', 'prov_name': '河南'},
    '三门峡': {'city_id': '772', 'prov_id': '76', 'prov_name': '河南'},
    '漯河': {'city_id': '766', 'prov_id': '76', 'prov_name': '河南'},
    '信阳': {'city_id': '776', 'prov_id': '76', 'prov_name': '河南'},
    '驻马店': {'city_id': '771', 'prov_id': '76', 'prov_name': '河南'},
    '郑州': {'city_id': '760', 'prov_id': '76', 'prov_name': '河南'},
    '吉安': {'city_id': '751', 'prov_id': '75', 'prov_name': '江西'},
    '南昌': {'city_id': '750', 'prov_id': '75', 'prov_name': '江西'},
    '新余': {'city_id': '753', 'prov_id': '75', 'prov_name': '江西'},
    '景德镇': {'city_id': '740', 'prov_id': '75', 'prov_name': '江西'},
    '抚州': {'city_id': '759', 'prov_id': '75', 'prov_name': '江西'},
    '宜春': {'city_id': '756', 'prov_id': '75', 'prov_name': '江西'},
    '上饶': {'city_id': '757', 'prov_id': '75', 'prov_name': '江西'},
    '九江': {'city_id': '755', 'prov_id': '75', 'prov_name': '江西'},
    '萍乡': {'city_id': '758', 'prov_id': '75', 'prov_name': '江西'},
    '鹰潭': {'city_id': '754', 'prov_id': '75', 'prov_name': '江西'},
    '赣州': {'city_id': '752', 'prov_id': '75', 'prov_name': '江西'},
    '西宁': {'city_id': '700', 'prov_id': '70', 'prov_name': '青海'},
    '海西': {'city_id': '704', 'prov_id': '70', 'prov_name': '青海'},
    '玉树': {'city_id': '709', 'prov_id': '70', 'prov_name': '青海'},
    '海南': {'city_id': '705', 'prov_id': '70', 'prov_name': '青海'},
    '格尔木': {'city_id': '702', 'prov_id': '70', 'prov_name': '青海'},
    '海北': {'city_id': '706', 'prov_id': '70', 'prov_name': '青海'},
    '黄南': {'city_id': '707', 'prov_id': '70', 'prov_name': '青海'},
    '海东': {'city_id': '7001', 'prov_id': '70', 'prov_name': '青海'},
    '来宾': {'city_id': '601', 'prov_id': '59', 'prov_name': '广西'},
    '崇左': {'city_id': '600', 'prov_id': '59', 'prov_name': '广西'},
    '玉林': {'city_id': '595', 'prov_id': '59', 'prov_name': '广西'},
    '梧州': {'city_id': '594', 'prov_id': '59', 'prov_name': '广西'},
    '南宁': {'city_id': '591', 'prov_id': '59', 'prov_name': '广西'},
    '防城港': {'city_id': '590', 'prov_id': '59', 'prov_name': '广西'},
    '钦州': {'city_id': '597', 'prov_id': '59', 'prov_name': '广西'},
    '贵港': {'city_id': '589', 'prov_id': '59', 'prov_name': '广西'},
    '贺州': {'city_id': '588', 'prov_id': '59', 'prov_name': '广西'},
    '柳州': {'city_id': '593', 'prov_id': '59', 'prov_name': '广西'},
    '河池': {'city_id': '598', 'prov_id': '59', 'prov_name': '广西'},
    '桂林': {'city_id': '592', 'prov_id': '59', 'prov_name': '广西'},
    '北海': {'city_id': '599', 'prov_id': '59', 'prov_name': '广西'},
    '百色': {'city_id': '596', 'prov_id': '59', 'prov_name': '广西'},
    '泉州': {'city_id': '480', 'prov_id': '38', 'prov_name': '福建'},
    '福州': {'city_id': '380', 'prov_id': '38', 'prov_name': '福建'},
    '莆田': {'city_id': '385', 'prov_id': '38', 'prov_name': '福建'},
    '三明': {'city_id': '389', 'prov_id': '38', 'prov_name': '福建'},
    '厦门': {'city_id': '390', 'prov_id': '38', 'prov_name': '福建'},
    '漳州': {'city_id': '395', 'prov_id': '38', 'prov_name': '福建'},
    '龙岩': {'city_id': '384', 'prov_id': '38', 'prov_name': '福建'},
    '南平': {'city_id': '387', 'prov_id': '38', 'prov_name': '福建'},
    '宁德': {'city_id': '386', 'prov_id': '38', 'prov_name': '福建'},
    '台州': {'city_id': '476', 'prov_id': '36', 'prov_name': '浙江'},
    '丽水': {'city_id': '469', 'prov_id': '36', 'prov_name': '浙江'},
    '宁波': {'city_id': '370', 'prov_id': '36', 'prov_name': '浙江'},
    '舟山': {'city_id': '364', 'prov_id': '36', 'prov_name': '浙江'},
    '衢州': {'city_id': '468', 'prov_id': '36', 'prov_name': '浙江'},
    '绍兴': {'city_id': '365', 'prov_id': '36', 'prov_name': '浙江'},
    '嘉兴': {'city_id': '363', 'prov_id': '36', 'prov_name': '浙江'},
    '湖州': {'city_id': '362', 'prov_id': '36', 'prov_name': '浙江'},
    '金华': {'city_id': '367', 'prov_id': '36', 'prov_name': '浙江'},
    '杭州': {'city_id': '360', 'prov_id': '36', 'prov_name': '浙江'},
    '温州': {'city_id': '361', 'prov_id': '36', 'prov_name': '浙江'},
    '淮安': {'city_id': '354', 'prov_id': '34', 'prov_name': '江苏'},
    '常州': {'city_id': '440', 'prov_id': '34', 'prov_name': '江苏'},
    '镇江': {'city_id': '343', 'prov_id': '34', 'prov_name': '江苏'},
    '连云港': {'city_id': '346', 'prov_id': '34', 'prov_name': '江苏'},
    '盐城': {'city_id': '348', 'prov_id': '34', 'prov_name': '江苏'},
    '无锡': {'city_id': '330', 'prov_id': '34', 'prov_name': '江苏'},
    '南京': {'city_id': '340', 'prov_id': '34', 'prov_name': '江苏'},
    '宿迁': {'city_id': '349', 'prov_id': '34', 'prov_name': '江苏'},
    '扬州': {'city_id': '430', 'prov_id': '34', 'prov_name': '江苏'},
    '苏州': {'city_id': '450', 'prov_id': '34', 'prov_name': '江苏'},
    '泰州': {'city_id': '445', 'prov_id': '34', 'prov_name': '江苏'},
    '徐州': {'city_id': '350', 'prov_id': '34', 'prov_name': '江苏'},
    '南通': {'city_id': '3401', 'prov_id': '34', 'prov_name': '江苏'},
    '安庆': {'city_id': '302', 'prov_id': '30', 'prov_name': '安徽'},
    '铜陵': {'city_id': '308', 'prov_id': '30', 'prov_name': '安徽'},
    '六安': {'city_id': '304', 'prov_id': '30', 'prov_name': '安徽'},
    '阜阳': {'city_id': '306', 'prov_id': '30', 'prov_name': '安徽'},
    '芜湖': {'city_id': '303', 'prov_id': '30', 'prov_name': '安徽'},
    '池州': {'city_id': '317', 'prov_id': '30', 'prov_name': '安徽'},
    '滁州': {'city_id': '312', 'prov_id': '30', 'prov_name': '安徽'},
    '宣城': {'city_id': '311', 'prov_id': '30', 'prov_name': '安徽'},
    '亳州': {'city_id': '318', 'prov_id': '30', 'prov_name': '安徽'},
    '淮北': {'city_id': '314', 'prov_id': '30', 'prov_name': '安徽'},
    '蚌埠': {'city_id': '301', 'prov_id': '30', 'prov_name': '安徽'},
    '合肥': {'city_id': '305', 'prov_id': '30', 'prov_name': '安徽'},
    '宿州': {'city_id': '313', 'prov_id': '30', 'prov_name': '安徽'},
    '黄山': {'city_id': '316', 'prov_id': '30', 'prov_name': '安徽'},
    '淮南': {'city_id': '307', 'prov_id': '30', 'prov_name': '安徽'},
    '马鞍山': {'city_id': '309', 'prov_id': '30', 'prov_name': '安徽'},
    '齐齐哈尔': {'city_id': '973', 'prov_id': '97', 'prov_name': '黑龙江'},
    '大庆': {'city_id': '981', 'prov_id': '97', 'prov_name': '黑龙江'},
    '鸡西': {'city_id': '991', 'prov_id': '97', 'prov_name': '黑龙江'},
    '伊春': {'city_id': '996', 'prov_id': '97', 'prov_name': '黑龙江'},
    '黑河': {'city_id': '990', 'prov_id': '97', 'prov_name': '黑龙江'},
    '佳木斯': {'city_id': '976', 'prov_id': '97', 'prov_name': '黑龙江'},
    '双鸭山': {'city_id': '994', 'prov_id': '97', 'prov_name': '黑龙江'},
    '大兴安岭': {'city_id': '995', 'prov_id': '97', 'prov_name': '黑龙江'},
    '鹤岗': {'city_id': '993', 'prov_id': '97', 'prov_name': '黑龙江'},
    '牡丹江': {'city_id': '988', 'prov_id': '97', 'prov_name': '黑龙江'},
    '绥化': {'city_id': '989', 'prov_id': '97', 'prov_name': '黑龙江'},
    '七台河': {'city_id': '992', 'prov_id': '97', 'prov_name': '黑龙江'},
    '哈尔滨': {'city_id': '971', 'prov_id': '97', 'prov_name': '黑龙江'},
    '葫芦岛': {'city_id': '922', 'prov_id': '91', 'prov_name': '辽宁'},
    '锦州': {'city_id': '916', 'prov_id': '91', 'prov_name': '辽宁'},
    '鞍山': {'city_id': '912', 'prov_id': '91', 'prov_name': '辽宁'},
    '阜新': {'city_id': '918', 'prov_id': '91', 'prov_name': '辽宁'},
    '本溪': {'city_id': '914', 'prov_id': '91', 'prov_name': '辽宁'},
    '大连': {'city_id': '940', 'prov_id': '91', 'prov_name': '辽宁'},
    '丹东': {'city_id': '915', 'prov_id': '91', 'prov_name': '辽宁'},
    '抚顺': {'city_id': '913', 'prov_id': '91', 'prov_name': '辽宁'},
    '铁岭': {'city_id': '911', 'prov_id': '91', 'prov_name': '辽宁'},
    '朝阳': {'city_id': '920', 'prov_id': '91', 'prov_name': '辽宁'},
    '营口': {'city_id': '917', 'prov_id': '91', 'prov_name': '辽宁'},
    '沈阳': {'city_id': '910', 'prov_id': '91', 'prov_name': '辽宁'},
    '盘锦': {'city_id': '921', 'prov_id': '91', 'prov_name': '辽宁'},
    '辽阳': {'city_id': '919', 'prov_id': '91', 'prov_name': '辽宁'},
    '吉林': {'city_id': '902', 'prov_id': '90', 'prov_name': '吉林'},
    '长春': {'city_id': '901', 'prov_id': '90', 'prov_name': '吉林'},
    '辽源': {'city_id': '906', 'prov_id': '90', 'prov_name': '吉林'},
    '白城': {'city_id': '907', 'prov_id': '90', 'prov_name': '吉林'},
    '通化': {'city_id': '905', 'prov_id': '90', 'prov_name': '吉林'},
    '四平': {'city_id': '903', 'prov_id': '90', 'prov_name': '吉林'},
    '延边': {'city_id': '909', 'prov_id': '90', 'prov_name': '吉林'},
    '松原': {'city_id': '904', 'prov_id': '90', 'prov_name': '吉林'},
    '白山': {'city_id': '908', 'prov_id': '90', 'prov_name': '吉林'},
    '伊犁': {'city_id': '898', 'prov_id': '89', 'prov_name': '新疆'},
    '和田': {'city_id': '955', 'prov_id': '89', 'prov_name': '新疆'},
    '克孜勒苏': {'city_id': '954', 'prov_id': '89', 'prov_name': '新疆'},
    '哈密': {'city_id': '900', 'prov_id': '89', 'prov_name': '新疆'},
    '塔城': {'city_id': '952', 'prov_id': '89', 'prov_name': '新疆'},
    '奎屯': {'city_id': '892', 'prov_id': '89', 'prov_name': '新疆'},
    '喀什': {'city_id': '897', 'prov_id': '89', 'prov_name': '新疆'},
    '阿克苏': {'city_id': '896', 'prov_id': '89', 'prov_name': '新疆'},
    '乌鲁木齐': {'city_id': '890', 'prov_id': '89', 'prov_name': '新疆'},
    '阿勒泰': {'city_id': '953', 'prov_id': '89', 'prov_name': '新疆'},
    '吐鲁番': {'city_id': '894', 'prov_id': '89', 'prov_name': '新疆'},
    '博乐': {'city_id': '951', 'prov_id': '89', 'prov_name': '新疆'},
    '石河子': {'city_id': '893', 'prov_id': '89', 'prov_name': '新疆'},
    '昌吉': {'city_id': '891', 'prov_id': '89', 'prov_name': '新疆'},
    '克拉玛依': {'city_id': '899', 'prov_id': '89', 'prov_name': '新疆'},
    '巴音郭楞': {'city_id': '895', 'prov_id': '89', 'prov_name': '新疆'},
    '固原': {'city_id': '885', 'prov_id': '88', 'prov_name': '宁夏'},
    '吴忠': {'city_id': '883', 'prov_id': '88', 'prov_name': '宁夏'},
    '石嘴山': {'city_id': '884', 'prov_id': '88', 'prov_name': '宁夏'},
    '中卫': {'city_id': '886', 'prov_id': '88', 'prov_name': '宁夏'},
    '银川': {'city_id': '880', 'prov_id': '88', 'prov_name': '宁夏'},
    '重庆': {'city_id': '831', 'prov_id': '83', 'prov_name': '重庆'},
    '仙桃/潜江/天门': {'city_id': '713', 'prov_id': '71', 'prov_name': '湖北'},
    '荆门': {'city_id': '724', 'prov_id': '71', 'prov_name': '湖北'},
    '恩施': {'city_id': '727', 'prov_id': '71', 'prov_name': '湖北'},
    '黄石': {'city_id': '715', 'prov_id': '71', 'prov_name': '湖北'},
    '武汉': {'city_id': '710', 'prov_id': '71', 'prov_name': '湖北'},
    '鄂州': {'city_id': '718', 'prov_id': '71', 'prov_name': '湖北'},
    '黄冈': {'city_id': '714', 'prov_id': '71', 'prov_name': '湖北'},
    '十堰': {'city_id': '7101', 'prov_id': '71', 'prov_name': '湖北'},
    '宜昌': {'city_id': '7102', 'prov_id': '71', 'prov_name': '湖北'},
    '襄阳': {'city_id': '7103', 'prov_id': '71', 'prov_name': '湖北'},
    '荆州': {'city_id': '7104', 'prov_id': '71', 'prov_name': '湖北'},
    '孝感': {'city_id': '7105', 'prov_id': '71', 'prov_name': '湖北'},
    '咸宁': {'city_id': '7106', 'prov_id': '71', 'prov_name': '湖北'},
    '随州': {'city_id': '7107', 'prov_id': '71', 'prov_name': '湖北'},
    '上海': {'city_id': '310', 'prov_id': '31', 'prov_name': '上海'},
    '大同': {'city_id': '193', 'prov_id': '19', 'prov_name': '山西'},
    '临汾': {'city_id': '197', 'prov_id': '19', 'prov_name': '山西'},
    '太原': {'city_id': '190', 'prov_id': '19', 'prov_name': '山西'},
    '运城': {'city_id': '196', 'prov_id': '19', 'prov_name': '山西'},
    '朔州': {'city_id': '199', 'prov_id': '19', 'prov_name': '山西'},
    '阳泉': {'city_id': '192', 'prov_id': '19', 'prov_name': '山西'},
    '晋城': {'city_id': '194', 'prov_id': '19', 'prov_name': '山西'},
    '长治': {'city_id': '195', 'prov_id': '19', 'prov_name': '山西'},
    '晋中': {'city_id': '191', 'prov_id': '19', 'prov_name': '山西'},
    '忻州': {'city_id': '198', 'prov_id': '19', 'prov_name': '山西'},
    '吕梁': {'city_id': '1910', 'prov_id': '19', 'prov_name': '山西'},
    '烟台': {'city_id': '161', 'prov_id': '17', 'prov_name': '山东'},
    '东营': {'city_id': '156', 'prov_id': '17', 'prov_name': '山东'},
    '济宁': {'city_id': '158', 'prov_id': '17', 'prov_name': '山东'},
    '威海': {'city_id': '152', 'prov_id': '17', 'prov_name': '山东'},
    '聊城': {'city_id': '174', 'prov_id': '17', 'prov_name': '山东'},
    '淄博': {'city_id': '150', 'prov_id': '17', 'prov_name': '山东'},
    '济南': {'city_id': '170', 'prov_id': '17', 'prov_name': '山东'},
    '德州': {'city_id': '173', 'prov_id': '17', 'prov_name': '山东'},
    '潍坊': {'city_id': '155', 'prov_id': '17', 'prov_name': '山东'},
    '枣庄': {'city_id': '157', 'prov_id': '17', 'prov_name': '山东'},
    '滨州': {'city_id': '151', 'prov_id': '17', 'prov_name': '山东'},
    '泰安': {'city_id': '172', 'prov_id': '17', 'prov_name': '山东'},
    '日照': {'city_id': '154', 'prov_id': '17', 'prov_name': '山东'},
    '莱芜': {'city_id': '160', 'prov_id': '17', 'prov_name': '山东'},
    '青岛': {'city_id': '166', 'prov_id': '17', 'prov_name': '山东'},
    '临沂': {'city_id': '175', 'prov_id': '17', 'prov_name': '山东'},
    '菏泽': {'city_id': '176', 'prov_id': '17', 'prov_name': '山东'},
    '天津': {'city_id': '130', 'prov_id': '13', 'prov_name': '天津'},
    '北京': {'city_id': '110', 'prov_id': '11', 'prov_name': '北京'},
    '呼和浩特': {'city_id': '101', 'prov_id': '10', 'prov_name': '内蒙古'},
    '赤峰': {'city_id': '107', 'prov_id': '10', 'prov_name': '内蒙古'},
    '包头': {'city_id': '102', 'prov_id': '10', 'prov_name': '内蒙古'},
    '兴安盟': {'city_id': '113', 'prov_id': '10', 'prov_name': '内蒙古'},
    '锡林郭勒盟': {'city_id': '111', 'prov_id': '10', 'prov_name': '内蒙古'},
    '通辽': {'city_id': '109', 'prov_id': '10', 'prov_name': '内蒙古'},
    '乌海': {'city_id': '106', 'prov_id': '10', 'prov_name': '内蒙古'},
    '鄂尔多斯': {'city_id': '104', 'prov_id': '10', 'prov_name': '内蒙古'},
    '巴彦淖尔': {'city_id': '105', 'prov_id': '10', 'prov_name': '内蒙古'},
    '阿拉善盟': {'city_id': '114', 'prov_id': '10', 'prov_name': '内蒙古'},
    '乌兰察布': {'city_id': '103', 'prov_id': '10', 'prov_name': '内蒙古'},
}